### ISSUE TITLE
Modifiable level and tags per event

### ISSUE THREAD

**Issue by JoeriA** [jspitzen/ravenr#6]
Be able to set level per event and use different tags per event, not per sentry object

**Comment by jspitzen** [comment]
@JoeriA Isn't this already possible? I think we can close this.

**Comment by JoeriA** [comment]
Ah whoops, I tagged the wrong issue while working on this, it is indeed implemented in https://github.com/jspitzen/ravenr/commit/48290311bd632ca3ee51ef649c27515a955cab44
